const { Book } = require("../models");

const bookData = [
  {
    author: "Chinua Achebe",
    genre: "fiction",
    cover: "image/things-fall-apart.jpg",
    link: "https://en.wikipedia.org/wiki/Things_Fall_Apart\n",
    title: "Things Fall Apart",
  },
  {
    author: "Hans Christian Andersen",
    genre: "fiction",
    cover: "image/fairy-tales.jpg",
    link: "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
    title: "Fairy tales",
  },
  {
    author: "Dante Alighieri",
    genre: "fiction",
    cover: "image/the-divine-comedy.jpg",
    link: "https://en.wikipedia.org/wiki/Divine_Comedy\n",
    title: "The Divine Comedy",
  },
  {
    author: "Unknown",
    genre: "fiction",
    cover: "image/the-epic-of-gilgamesh.jpg",
    link: "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh\n",
    title: "The Epic Of Gilgamesh",
  },
  {
    author: "Unknown",
    genre: "fiction",
    cover: "image/the-book-of-job.jpg",
    link: "https://en.wikipedia.org/wiki/Book_of_Job\n",
    title: "The Book Of Job",
  },
  {
    author: "Unknown",
    genre: "fiction",
    cover: "image/one-thousand-and-one-nights.jpg",
    link: "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n",
    title: "One Thousand and One Nights",
  },
  {
    author: "Unknown",
    genre: "fiction",
    cover: "image/njals-saga.jpg",
    link: "https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga\n",
    title: "Nj\u00e1l's Saga",
  },
  {
    author: "Jane Austen",
    genre: "fiction",
    cover: "image/pride-and-prejudice.jpg",
    link: "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
    title: "Pride and Prejudice",
  },
  {
    author: "Honor\u00e9 de Balzac",
    genre: "fiction",
    cover: "image/le-pere-goriot.jpg",
    link: "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot\n",
    title: "Le P\u00e8re Goriot",
  },
  {
    author: "Samuel Beckett",
    genre: "fiction",
    cover: "image/molloy-malone-dies-the-unnamable.jpg",
    link: "https://en.wikipedia.org/wiki/Molloy_(novel)\n",
    title: "Molloy, Malone Dies, The Unnamable, the trilogy",
  },
  {
    author: "Giovanni Boccaccio",
    genre: "fiction",
    cover: "image/the-decameron.jpg",
    link: "https://en.wikipedia.org/wiki/The_Decameron\n",
    title: "The Decameron",
  },
  {
    author: "Jorge Luis Borges",
    genre: "fiction",
    cover: "image/ficciones.jpg",
    link: "https://en.wikipedia.org/wiki/Ficciones\n",
    title: "Ficciones",
  },
  {
    author: "Emily Bront\u00eb",
    genre: "fiction",
    cover: "image/wuthering-heights.jpg",
    link: "https://en.wikipedia.org/wiki/Wuthering_Heights\n",
    title: "Wuthering Heights",
  },
  {
    author: "Albert Camus",
    genre: "fiction",
    cover: "image/l-etranger.jpg",
    link: "https://en.wikipedia.org/wiki/The_Stranger_(novel)\n",
    title: "The Stranger",
  },
  {
    author: "Paul Celan",
    genre: "fiction",
    cover: "image/poems-paul-celan.jpg",
    link: "\n",
    title: "Poems",
  },
  {
    author: "Louis-Ferdinand C\u00e9line",
    genre: "drama",
    cover: "image/voyage-au-bout-de-la-nuit.jpg",
    link: "https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night\n",
    title: "Journey to the End of the Night",
  },
  {
    author: "Miguel de Cervantes",
    genre: "drama",
    cover: "image/don-quijote-de-la-mancha.jpg",
    link: "https://en.wikipedia.org/wiki/Don_Quixote\n",
    title: "Don Quijote De La Mancha",
  },
  {
    author: "Geoffrey Chaucer",
    genre: "drama",
    cover: "image/the-canterbury-tales.jpg",
    link: "https://en.wikipedia.org/wiki/The_Canterbury_Tales\n",
    title: "The Canterbury Tales",
  },
  {
    author: "Anton Chekhov",
    genre: "drama",
    cover: "image/stories-of-anton-chekhov.jpg",
    link: "https://en.wikipedia.org/wiki/List_of_short_stories_by_Anton_Chekhov\n",
    title: "Stories",
  },
  {
    author: "Joseph Conrad",
    genre: "drama",
    cover: "image/nostromo.jpg",
    link: "https://en.wikipedia.org/wiki/Nostromo\n",
    title: "Nostromo",
  },
  {
    author: "Charles Dickens",
    genre: "drama",
    cover: "image/great-expectations.jpg",
    link: "https://en.wikipedia.org/wiki/Great_Expectations\n",
    title: "Great Expectations",
  },
  {
    author: "Denis Diderot",
    genre: "drama",
    cover: "image/jacques-the-fatalist.jpg",
    link: "https://en.wikipedia.org/wiki/Jacques_the_Fatalist\n",
    title: "Jacques the Fatalist",
  },
  {
    author: "Alfred D\u00f6blin",
    genre: "drama",
    cover: "image/berlin-alexanderplatz.jpg",
    link: "https://en.wikipedia.org/wiki/Berlin_Alexanderplatz\n",
    title: "Berlin Alexanderplatz",
  },
  {
    author: "Fyodor Dostoevsky",
    genre: "drama",
    cover: "image/crime-and-punishment.jpg",
    link: "https://en.wikipedia.org/wiki/Crime_and_Punishment\n",
    title: "Crime and Punishment",
  },
  {
    author: "Fyodor Dostoevsky",
    genre: "drama",
    cover: "image/the-idiot.jpg",
    link: "https://en.wikipedia.org/wiki/The_Idiot\n",
    title: "The Idiot",
  },
  {
    author: "Fyodor Dostoevsky",
    genre: "drama",
    cover: "image/the-possessed.jpg",
    link: "https://en.wikipedia.org/wiki/Demons_(Dostoyevsky_novel)\n",
    title: "The Possessed",
  },
  {
    author: "Fyodor Dostoevsky",
    genre: "drama",
    cover: "image/the-brothers-karamazov.jpg",
    link: "https://en.wikipedia.org/wiki/The_Brothers_Karamazov\n",
    title: "The Brothers Karamazov",
  },
  {
    author: "George Eliot",
    genre: "drama",
    cover: "image/middlemarch.jpg",
    link: "https://en.wikipedia.org/wiki/Middlemarch\n",
    title: "Middlemarch",
  },
  {
    author: "Ralph Ellison",
    genre: "drama",
    cover: "image/invisible-man.jpg",
    link: "https://en.wikipedia.org/wiki/Invisible_Man\n",
    title: "Invisible Man",
  },
  {
    author: "Euripides",
    genre: "drama",
    cover: "image/medea.jpg",
    link: "https://en.wikipedia.org/wiki/Medea_(play)\n",
    title: "Medea",
  },
  {
    author: "William Faulkner",
    genre: "history",
    cover: "image/absalom-absalom.jpg",
    link: "https://en.wikipedia.org/wiki/Absalom,_Absalom!\n",
    title: "Absalom, Absalom!",
  },
  {
    author: "William Faulkner",
    genre: "history",
    cover: "image/the-sound-and-the-fury.jpg",
    link: "https://en.wikipedia.org/wiki/The_Sound_and_the_Fury\n",
    title: "The Sound and the Fury",
  },
  {
    author: "Gustave Flaubert",
    genre: "history",
    cover: "image/madame-bovary.jpg",
    link: "https://en.wikipedia.org/wiki/Madame_Bovary\n",
    title: "Madame Bovary",
  },
  {
    author: "Gustave Flaubert",
    genre: "history",
    cover: "image/l-education-sentimentale.jpg",
    link: "https://en.wikipedia.org/wiki/Sentimental_Education\n",
    title: "Sentimental Education",
  },
  {
    author: "Federico Garc\u00eda Lorca",
    genre: "history",
    cover: "image/gypsy-ballads.jpg",
    link: "https://en.wikipedia.org/wiki/Gypsy_Ballads\n",
    title: "Gypsy Ballads",
  },
  {
    author: "Gabriel Garc\u00eda M\u00e1rquez",
    genre: "history",
    cover: "image/one-hundred-years-of-solitude.jpg",
    link: "https://en.wikipedia.org/wiki/One_Hundred_Years_of_Solitude\n",
    title: "One Hundred Years of Solitude",
  },
  {
    author: "Gabriel Garc\u00eda M\u00e1rquez",
    genre: "history",
    cover: "image/love-in-the-time-of-cholera.jpg",
    link: "https://en.wikipedia.org/wiki/Love_in_the_Time_of_Cholera\n",
    title: "Love in the Time of Cholera",
  },
  {
    author: "Johann Wolfgang von Goethe",
    genre: "history",
    cover: "image/faust.jpg",
    link: "https://en.wikipedia.org/wiki/Goethe%27s_Faust\n",
    title: "Faust",
  },
  {
    author: "Nikolai Gogol",
    genre: "history",
    cover: "image/dead-souls.jpg",
    link: "https://en.wikipedia.org/wiki/Dead_Souls\n",
    title: "Dead Souls",
  },
  {
    author: "G\u00fcnter Grass",
    genre: "history",
    cover: "image/the-tin-drum.jpg",
    link: "https://en.wikipedia.org/wiki/The_Tin_Drum\n",
    title: "The Tin Drum",
  },
  {
    author: "Jo\u00e3o Guimar\u00e3es Rosa",
    genre: "history",
    cover: "image/the-devil-to-pay-in-the-backlands.jpg",
    link: "https://en.wikipedia.org/wiki/The_Devil_to_Pay_in_the_Backlands\n",
    title: "The Devil to Pay in the Backlands",
  },
  {
    author: "Knut Hamsun",
    genre: "history",
    cover: "image/hunger.jpg",
    link: "https://en.wikipedia.org/wiki/Hunger_(Hamsun_novel)\n",
    title: "Hunger",
  },
  {
    author: "Ernest Hemingway",
    genre: "history",
    cover: "image/the-old-man-and-the-sea.jpg",
    link: "https://en.wikipedia.org/wiki/The_Old_Man_and_the_Sea\n",
    title: "The Old Man and the Sea",
  },
  {
    author: "Homer",
    genre: "history",
    cover: "image/the-iliad-of-homer.jpg",
    link: "https://en.wikipedia.org/wiki/Iliad\n",
    title: "Iliad",
  },
  {
    author: "Homer",
    genre: "history",
    cover: "image/the-odyssey-of-homer.jpg",
    link: "https://en.wikipedia.org/wiki/Odyssey\n",
    title: "Odyssey",
  },
  {
    author: "Henrik Ibsen",
    genre: "adventure",
    cover: "image/a-Dolls-house.jpg",
    link: "https://en.wikipedia.org/wiki/A_Doll%27s_House\n",
    title: "A Doll's House",
  },
  {
    author: "James Joyce",
    genre: "adventure",
    cover: "image/ulysses.jpg",
    link: "https://en.wikipedia.org/wiki/Ulysses_(novel)\n",
    title: "Ulysses",
  },
  {
    author: "Franz Kafka",
    genre: "adventure",
    cover: "image/stories-of-franz-kafka.jpg",
    link: "https://en.wikipedia.org/wiki/Franz_Kafka_bibliography#Short_stories\n",
    title: "Stories",
  },
  {
    author: "Franz Kafka",
    genre: "adventure",
    cover: "image/the-trial.jpg",
    link: "https://en.wikipedia.org/wiki/The_Trial\n",
    title: "The Trial",
  },
  {
    author: "Franz Kafka",
    genre: "adventure",
    cover: "image/the-castle.jpg",
    link: "https://en.wikipedia.org/wiki/The_Castle_(novel)\n",
    title: "The Castle",
  },
  {
    author: "K\u0101lid\u0101sa",
    genre: "adventure",
    cover: "image/the-recognition-of-shakuntala.jpg",
    link: "https://en.wikipedia.org/wiki/Abhij%C3%B1%C4%81na%C5%9B%C4%81kuntalam\n",
    title: "The recognition of Shakuntala",
  },
  {
    author: "Yasunari Kawabata",
    genre: "adventure",
    cover: "image/the-sound-of-the-mountain.jpg",
    link: "https://en.wikipedia.org/wiki/The_Sound_of_the_Mountain\n",
    title: "The Sound of the Mountain",
  },
  {
    author: "Nikos Kazantzakis",
    genre: "adventure",
    cover: "image/zorba-the-greek.jpg",
    link: "https://en.wikipedia.org/wiki/Zorba_the_Greek\n",
    title: "Zorba the Greek",
  },
  {
    author: "D. H. Lawrence",
    genre: "adventure",
    cover: "image/sons-and-lovers.jpg",
    link: "https://en.wikipedia.org/wiki/Sons_and_Lovers\n",
    title: "Sons and Lovers",
  },
  {
    author: "Halld\u00f3r Laxness",
    genre: "adventure",
    cover: "image/independent-people.jpg",
    link: "https://en.wikipedia.org/wiki/Independent_People\n",
    title: "Independent People",
  },
  {
    author: "Giacomo Leopardi",
    genre: "adventure",
    cover: "image/poems-giacomo-leopardi.jpg",
    link: "\n",
    title: "Poems",
  },
  {
    author: "Doris Lessing",
    genre: "adventure",
    cover: "image/the-golden-notebook.jpg",
    link: "https://en.wikipedia.org/wiki/The_Golden_Notebook\n",
    title: "The Golden Notebook",
  },
  {
    author: "Astrid Lindgren",
    genre: "adventure",
    cover: "image/pippi-longstocking.jpg",
    link: "https://en.wikipedia.org/wiki/Pippi_Longstocking\n",
    title: "Pippi Longstocking",
  },
  {
    author: "Lu Xun",
    genre: "adventure",
    cover: "image/diary-of-a-madman.jpg",
    link: "https://en.wikipedia.org/wiki/A_Madman%27s_Diary\n",
    title: "Diary of a Madman",
  },
  {
    author: "Naguib Mahfouz",
    genre: "adventure",
    cover: "image/children-of-gebelawi.jpg",
    link: "https://en.wikipedia.org/wiki/Children_of_Gebelawi\n",
    title: "Children of Gebelawi",
  },
  {
    author: "Thomas Mann",
    genre: "science",
    cover: "image/buddenbrooks.jpg",
    link: "https://en.wikipedia.org/wiki/Buddenbrooks\n",
    title: "Buddenbrooks",
  },
  {
    author: "Thomas Mann",
    genre: "science",
    cover: "image/the-magic-mountain.jpg",
    link: "https://en.wikipedia.org/wiki/The_Magic_Mountain\n",
    title: "The Magic Mountain",
  },
  {
    author: "Herman Melville",
    genre: "science",
    cover: "image/moby-dick.jpg",
    link: "https://en.wikipedia.org/wiki/Moby-Dick\n",
    title: "Moby Dick",
  },
  {
    author: "Michel de Montaigne",
    genre: "science",
    cover: "image/essais.jpg",
    link: "https://en.wikipedia.org/wiki/Essays_(Montaigne)\n",
    title: "Essays",
  },
  {
    author: "Elsa Morante",
    genre: "science",
    cover: "image/history.jpg",
    link: "https://en.wikipedia.org/wiki/History_(novel)\n",
    title: "History",
  },
  {
    author: "Toni Morrison",
    genre: "science",
    cover: "image/beloved.jpg",
    link: "https://en.wikipedia.org/wiki/Beloved_(novel)\n",
    title: "Beloved",
  },
  {
    author: "Murasaki Shikibu",
    genre: "science",
    cover: "image/the-tale-of-genji.jpg",
    link: "https://en.wikipedia.org/wiki/The_Tale_of_Genji\n",
    title: "The Tale of Genji",
  },
  {
    author: "Robert Musil",
    genre: "science",
    cover: "image/the-man-without-qualities.jpg",
    link: "https://en.wikipedia.org/wiki/The_Man_Without_Qualities\n",
    title: "The Man Without Qualities",
  },
  {
    author: "Vladimir Nabokov",
    genre: "science",
    cover: "image/lolita.jpg",
    link: "https://en.wikipedia.org/wiki/Lolita\n",
    title: "Lolita",
  },
  {
    author: "George Orwell",
    genre: "science",
    cover: "image/nineteen-eighty-four.jpg",
    link: "https://en.wikipedia.org/wiki/Nineteen_Eighty-Four\n",
    title: "Nineteen Eighty-Four",
  },
  {
    author: "Ovid",
    genre: "science",
    cover: "image/the-metamorphoses-of-ovid.jpg",
    link: "https://en.wikipedia.org/wiki/Metamorphoses\n",
    title: "Metamorphoses",
  },
  {
    author: "Fernando Pessoa",
    genre: "science",
    cover: "image/the-book-of-disquiet.jpg",
    link: "https://en.wikipedia.org/wiki/The_Book_of_Disquiet\n",
    title: "The Book of Disquiet",
  },
  {
    author: "Edgar Allan Poe",
    genre: "science",
    cover: "image/tales-and-poems-of-edgar-allan-poe.jpg",
    link: "https://en.wikipedia.org/wiki/Edgar_Allan_Poe_bibliography#Tales\n",
    title: "Tales",
  },
  {
    author: "Marcel Proust",
    genre: "science",
    cover: "image/a-la-recherche-du-temps-perdu.jpg",
    link: "https://en.wikipedia.org/wiki/In_Search_of_Lost_Time\n",
    title: "In Search of Lost Time",
  },
  {
    author: "Fran\u00e7ois Rabelais",
    genre: "science",
    cover: "image/gargantua-and-pantagruel.jpg",
    link: "https://en.wikipedia.org/wiki/Gargantua_and_Pantagruel\n",
    title: "Gargantua and Pantagruel",
  },
  {
    author: "Juan Rulfo",
    genre: "philosophy",
    cover: "image/pedro-paramo.jpg",
    link: "https://en.wikipedia.org/wiki/Pedro_P%C3%A1ramo\n",
    title: "Pedro P\u00e1ramo",
  },
  {
    author: "Rumi",
    genre: "philosophy",
    cover: "image/the-masnavi.jpg",
    link: "https://en.wikipedia.org/wiki/Masnavi\n",
    title: "The Masnavi",
  },
  {
    author: "Salman Rushdie",
    genre: "philosophy",
    cover: "image/midnights-children.jpg",
    link: "https://en.wikipedia.org/wiki/Midnight%27s_Children\n",
    title: "Midnight's Children",
  },
  {
    author: "Saadi",
    genre: "philosophy",
    cover: "image/bostan.jpg",
    link: "https://en.wikipedia.org/wiki/Bustan_(book)\n",
    title: "Bostan",
  },
  {
    author: "Tayeb Salih",
    genre: "philosophy",
    cover: "image/season-of-migration-to-the-north.jpg",
    link: "https://en.wikipedia.org/wiki/Season_of_Migration_to_the_North\n",
    title: "Season of Migration to the North",
  },
  {
    author: "Jos\u00e9 Saramago",
    genre: "philosophy",
    cover: "image/blindness.jpg",
    link: "https://en.wikipedia.org/wiki/Blindness_(novel)\n",
    title: "Blindness",
  },
  {
    author: "William Shakespeare",
    genre: "philosophy",
    cover: "image/hamlet.jpg",
    link: "https://en.wikipedia.org/wiki/Hamlet\n",
    title: "Hamlet",
  },
  {
    author: "William Shakespeare",
    genre: "philosophy",
    cover: "image/king-lear.jpg",
    link: "https://en.wikipedia.org/wiki/King_Lear\n",
    title: "King Lear",
  },
  {
    author: "William Shakespeare",
    genre: "philosophy",
    cover: "image/othello.jpg",
    link: "https://en.wikipedia.org/wiki/Othello\n",
    title: "Othello",
  },
  {
    author: "Sophocles",
    genre: "philosophy",
    cover: "image/oedipus-the-king.jpg",
    link: "https://en.wikipedia.org/wiki/Oedipus_the_King\n",
    title: "Oedipus the King",
  },
  {
    author: "Stendhal",
    genre: "philosophy",
    cover: "image/le-rouge-et-le-noir.jpg",
    link: "https://en.wikipedia.org/wiki/The_Red_and_the_Black\n",
    title: "The Red and the Black",
  },
  {
    author: "Laurence Sterne",
    genre: "philosophy",
    cover: "image/the-life-and-opinions-of-tristram-shandy.jpg",
    link: "https://en.wikipedia.org/wiki/The_Life_and_Opinions_of_Tristram_Shandy,_Gentleman\n",
    title: "The Life And Opinions of Tristram Shandy",
  },
  {
    author: "Italo Svevo",
    genre: "philosophy",
    cover: "image/confessions-of-zeno.jpg",
    link: "https://en.wikipedia.org/wiki/Zeno%27s_Conscience\n",
    title: "Confessions of Zeno",
  },
  {
    author: "Jonathan Swift",
    genre: "philosophy",
    cover: "image/gullivers-travels.jpg",
    link: "https://en.wikipedia.org/wiki/Gulliver%27s_Travels\n",
    title: "Gulliver's Travels",
  },
  {
    author: "Leo Tolstoy",
    genre: "philosophy",
    cover: "image/war-and-peace.jpg",
    link: "https://en.wikipedia.org/wiki/War_and_Peace\n",
    title: "War and Peace",
  },
  {
    author: "Leo Tolstoy",
    genre: "adventure",
    cover: "image/anna-karenina.jpg",
    link: "https://en.wikipedia.org/wiki/Anna_Karenina\n",
    title: "Anna Karenina",
  },
  {
    author: "Leo Tolstoy",
    genre: "adventure",
    cover: "image/the-death-of-ivan-ilyich.jpg",
    link: "https://en.wikipedia.org/wiki/The_Death_of_Ivan_Ilyich\n",
    title: "The Death of Ivan Ilyich",
  },
  {
    author: "Mark Twain",
    genre: "adventure",
    cover: "image/the-adventures-of-huckleberry-finn.jpg",
    link: "https://en.wikipedia.org/wiki/Adventures_of_Huckleberry_Finn\n",
    title: "The Adventures of Huckleberry Finn",
  },
  {
    author: "Valmiki",
    genre: "adventure",
    cover: "image/ramayana.jpg",
    link: "https://en.wikipedia.org/wiki/Ramayana\n",
    title: "Ramayana",
  },
  {
    author: "Virgil",
    genre: "adventure",
    cover: "image/the-aeneid.jpg",
    link: "https://en.wikipedia.org/wiki/Aeneid\n",
    title: "The Aeneid",
  },
  {
    author: "Vyasa",
    genre: "fiction",
    cover: "image/the-mahab-harata.jpg",
    link: "https://en.wikipedia.org/wiki/Mahabharata\n",
    title: "Mahabharata",
  },
  {
    author: "Walt Whitman",
    genre: "fiction",
    cover: "image/leaves-of-grass.jpg",
    link: "https://en.wikipedia.org/wiki/Leaves_of_Grass\n",
    title: "Leaves of Grass",
  },
  {
    author: "Virginia Woolf",
    genre: "fiction",
    cover: "image/mrs-dalloway.jpg",
    link: "https://en.wikipedia.org/wiki/Mrs_Dalloway\n",
    title: "Mrs Dalloway",
  },
  {
    author: "Virginia Woolf",
    genre: "fiction",
    cover: "image/to-the-lighthouse.jpg",
    link: "https://en.wikipedia.org/wiki/To_the_Lighthouse\n",
    title: "To the Lighthouse",
  },
  {
    author: "Marguerite Yourcenar",
    genre: "fiction",
    cover: "image/memoirs-of-hadrian.jpg",
    link: "https://en.wikipedia.org/wiki/Memoirs_of_Hadrian\n",
    title: "Memoirs of Hadrian",
  },
];

const seedBooks = () => Book.bulkCreate(bookData);

module.exports = seedBooks;
